/* 
**  mod_auth_openid.c -- Apache sample auth_openid module
**  [Autogenerated via ``apxs -n auth_openid -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_auth_openid.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /auth_openid in as follows:
**
**    #   httpd.conf
**    LoadModule auth_openid_module modules/mod_auth_openid.so
**    <Location /auth_openid>
**    SetHandler auth_openid
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /auth_openid and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/auth_openid 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_auth_openid.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

typedef struct {
  int val1;
}auth_openid_cfg;

/* initialize directory config data */
static void *create_dir_config(apr_pool_t *p, char *dir)
{
  auth_openid_cfg *conf = (auth_openid_cfg *)apr_pcalloc(p, sizeof(auth_openid_cfg));
  return conf;
}

/* The sample content handler */
static int auth_openid_handler(request_rec *r)
{
    if (strcmp(r->handler, "auth_openid")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

    if (!r->header_only)
        ap_rputs("The sample page from mod_auth_openid.c\n", r);
    return OK;
}

static void auth_openid_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(auth_openid_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA auth_openid_module = {
    STANDARD20_MODULE_STUFF, 
    create_dir_config,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    auth_openid_register_hooks  /* register hooks                      */
};

