/* 
**  mod_cs_test.c -- Apache sample cs_test module
**  [Autogenerated via ``apxs -n cs_test -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_cs_test.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /cs_test in as follows:
**
**    #   httpd.conf
**    LoadModule cs_test_module modules/mod_cs_test.so
**    <Location /cs_test>
**    SetHandler cs_test
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /cs_test and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/cs_test 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_cs_test.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

/* The sample content handler */
static int cs_test_handler(request_rec *r)
{
    if (strcmp(r->handler, "cs_test")) {
        return DECLINED;
    }
    r->content_type = "text/html";      

    if (!r->header_only)
        ap_rputs("The sample page from mod_cs_test.c\n", r);
    return OK;
}

static void cs_test_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(cs_test_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA cs_test_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    cs_test_register_hooks  /* register hooks                      */
};

